default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: <%= ENV['DATABASE_URL']%>

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  url: <%= ENV['DATABASE_URL']%>
